let almacen = 
[
{
    id: '00', 
    imagen: 'pan 1.jpg',
    nombre:'Pan de Mesa Lactal',
    detalle: 'Pan De Mesa Blanco Lactal Bsa 500 Grm',
    precio: '$250',
},
{
    id: '01', 
    imagen: 'pan 2.jpg',
    nombre:'Pan de Mesa Fargo',
    detalle: 'Pan Salvado Plus Chico Fargo Bsa 350 Grm',
    precio: '$250',
},
{
    id: '02', 
    imagen: 'papas fritas.jpg',
    nombre:'Papas Fritas Lays',
    detalle: 'Papas Fritas Clásicas Lays Paq 249 Grm',
    precio: '$430',
},
{
    id: '03', 
    imagen: 'fideos 1.jpg',
    nombre:'Fideos Lucchetti',
    detalle: 'Tirabuzon LUCCHETTI Paquete 500 Gr',
    precio: '$70',
},
{
    id: '04', 
    imagen: 'fideos 2.jpg',
    nombre:'Fideos Lucchetti',
    detalle: 'Tirabuzon verduras LUCCHETTI Paquete 500 Gr',
    precio: '$130',
},
{
    id: '05', 
    imagen: 'fideos 3.jpg',
    nombre:'Fideos La Campagnola',
    detalle: 'Fid.Semola De Trig Tallarin La Campagnola Paq 500 Grm',
    precio: '$110',
},
{
    id: '06', 
    imagen: 'fideos 4.jpg',
    nombre:'Fideos Lucchetti',
    detalle: 'Coditos LUCCHETTI Paquete 500 Gr',
    precio: '$100',
},
{
    id: '07', 
    imagen: 'fideos 5.jpg',
    nombre:'Fideos Lucchetti',
    detalle: 'Mostachol LUCCHETTI Paquete 500 Gr',
    precio: '$100',
},
{
    id: '08', 
    imagen: 'lasagna.jpg',
    nombre:'Lasagna Matarazzo',
    detalle: 'Lasagna Matarazzo Paq 400 Grm',
    precio: '$260',
},
{
    id: '09', 
    imagen: 'ñoquis.jpg',
    nombre:'Ñoquis La Salteña',
    detalle: 'Ñoquis . La Salteña Ban 900 Grm',
    precio: '$400',
},
{
    id: '10', 
    imagen: 'capelletini.jpg',
    nombre:'Capelletini Giacomo',
    detalle: 'Capelletini Verdura Giacomo Paq 500 Grm',
    precio: '$330',
},
{
    id: '11', 
    imagen: 'arroz 1.jpg',
    nombre:'Arroz Ciudad del Lago',
    detalle: 'Arroz Largo Fino CIUDAD DEL LAGO Paquete 1 Kg',
    precio: '$100',
},
{
    id: '12', 
    imagen: 'arroz 2.jpg',
    nombre:'Arroz Gallo',
    detalle: 'Arroz Largo Fino GALLO Versátil Paquete 1 Kg',
    precio: '$115',
},
{
    id: '13', 
    imagen: 'arroz 3.jpg',
    nombre:'Arroz Lucchetti',
    detalle: 'Arroz Parboil LUCCHETTI Estuche X1 Kg',
    precio: '$125',
},
{
    id: '14', 
    imagen: 'arroz 4.jpg',
    nombre:'Arroz Molinos',
    detalle: 'Arroz Integ. . MOLINOS ALA Paq 1 Kgm',
    precio: '$160',
},
{
    id: '15', 
    imagen: 'harina 1.jpg',
    nombre:'Harina Favorita',
    detalle: 'Harina Trigo 000 FAVORITA Paq 1 Kgm',
    precio: '$70',
},
{
    id: '16', 
    imagen: 'harina 2.jpg',
    nombre:'Harina Cañuelas',
    detalle: 'Harina Ultra Refinada Cañuelas Paq 1 Kgm',
    precio: '$70',
},
{
    id: '17', 
    imagen: 'harina 3.jpg',
    nombre:'Harina Pureza',
    detalle: 'Harina Leudante Ultra Refinada Pureza Paq 1 Kgm',
    precio: '$150',
},
{
    id: '18', 
    imagen: 'galles 1.jpg',
    nombre:'Galletitas Criollitas',
    detalle: 'Galletitas . Criollitas Paq 300 Grm',
    precio: '$105',
},
{
    id: '19', 
    imagen: 'galles 2.jpg',
    nombre:'Galletitas OREO',
    detalle: 'Galletitas OREO Mini Clásica 50gr',
    precio: '$55',
},
{
    id: '20', 
    imagen: 'galles 3.jpg',
    nombre:'Galletitas Chocolinas',
    detalle: 'Gall.Dulces Chocolat Chocolinas Paq 250 Grm',
    precio: '$105',
},
{
    id: '21', 
    imagen: 'galles 4.jpg',
    nombre:'Galletitas Don Satur',
    detalle: 'Pepas DON SATUR Bsa 300 Grm',
    precio: '$120',
},
{
    id: '22', 
    imagen: 'galles 5.jpg',
    nombre:'Galletitas Opera',
    detalle: 'Gall.Rellena Opera Opera Pak 220 Grm',
    precio: '$130',
},
{
    id: '23', 
    imagen: 'galles 6.jpg',
    nombre:'Galletitas Bagley',
    detalle: 'Gall.Dulces Surtido Bagley Paq 390 Grm',
    precio: '$210',
},
{
    id: '24', 
    imagen: 'galles 7.jpg',
    nombre:'Galletitas Terrabusi',
    detalle: 'Galletitas Terrabusi VARIEDAD Clásica 610grs',
    precio: '$350',
},

{
    id: '25', 
    imagen: 'galles 8.jpg',
    nombre:'Galletitas 9 de Oro',
    detalle: 'Bizcochos Clásicos 9 De Oro Paq 215 Grm',
    precio: '$100',
},

{
    id: '26', 
    imagen: 'galles 9.jpg',
    nombre:'Galletitas 9 de Oro',
    detalle: 'Bizcochos Agridulces 9 De Oro Paq 215 Grm',
    precio: '$100',
},

{
    id: '27', 
    imagen: 'galles 10.jpg',
    nombre:'Galletitas Oreo',
    detalle: 'Galletitas Rellena Veggie Tripack Oreo Paq 354 Grm',
    precio: '$430',
},

{
    id: '28', 
    imagen: 'chocolate.jpg',
    nombre:'Chocolate Milka',
    detalle: 'Chocolate MILKA Relleno Oreo Paq 100 Grm',
    precio: '$410',
},

{
    id: '29', 
    imagen: 'chocolate 2.jpg',
    nombre:'Chocolate Milka',
    detalle: 'Chocolate Con Almendras Milka Fwp 110 Grm',
    precio: '$450',
},

{
    id: '30', 
    imagen: 'chocolate 3.jpg',
    nombre:'Alfajor Milka',
    detalle: 'Alfajor MILKA Chocolate 70 Gr X 1 Uni',
    precio: '$100',
},

{
    id: '31', 
    imagen: 'chocolate 4.jpg',
    nombre:'Chocolate Milka',
    detalle: 'Chocolate MILKA C/ Dulce De Leche Tab 67.5 Grm',
    precio: '$230',
},

{
    id: '32', 
    imagen: 'turron.jpg',
    nombre:'Turron Mani Arcor',
    detalle: 'Turron Mani ARCOR Paq 25 Grm',
    precio: '$30',
},

{
    id: '33', 
    imagen: 'gomitas.jpg',
    nombre:'Gomitas Mogul',
    detalle: 'Pastillas De Goma Rodajas Ácidas Mogul Fwp 50 Grm',
    precio: '$70',
},

{
    id: '34', 
    imagen: 'alfajor.jpg',
    nombre:'Alfajor Bon o Bon',
    detalle: 'Alfajor Bon O Bon 40 Gr X 1 Uni',
    precio: '$70',
},

{
    id: '35', 
    imagen: 'confites.jpg',
    nombre:'Sugus Confitados',
    detalle: 'Caramelos Sugus Confitados Est 50 Grm',
    precio: '$100',
},
{
    id: '36', 
    imagen: 'yerba 1.jpg',
    nombre:'Yerba Mate Amanda',
    detalle: 'Yerba Mate AMANDA Paquete 500 Gr',
    precio: '$180',
},
{
    id: '37', 
    imagen: 'yerba 2.jpg',
    nombre:'Yerba Mate Cruz de Malta',
    detalle: 'Yerba Mate CRUZ DE MALTA Con Palo Paquete 500 Gr',
    precio: '$220',
},
{
    id: '38', 
    imagen: 'yerba 3.jpg',
    nombre:'Yerba Mate Mañanita',
    detalle: 'Yerba Mate 4 Flex MAÑANITA 1 Kg',
    precio: '$230',
},
{
    id: '39', 
    imagen: 'cafe 1.jpg',
    nombre:'Café Arlistan',
    detalle: 'Café Instantaneo Torrado Selección Arlistan Fra 50 Grm',
    precio: '$230',
},
{
    id: '40', 
    imagen: 'cafe 2.jpg',
    nombre:'Café La Virginia',
    detalle: 'Café Molido LA VIRGINIA Paquete 250 Gr',
    precio: '$310',
},
{
    id: '41', 
    imagen: 'cafe 3.jpg',
    nombre:'Café Nescafe',
    detalle: 'Cafe Instantaneo Suave Nescafe Fra 100 Grm',
    precio: '$750',
},
{
    id: '42', 
    imagen: 'te 1.jpg',
    nombre:'Té Taragui',
    detalle: 'Te X100 Saq Filtr Taragui Est 100 Uni',
    precio: '$300',
},
{
    id: '43', 
    imagen: 'te 2.jpg',
    nombre:'Té La Virginia',
    detalle: 'Te Verde Citrus LA VIRGINIA Est 20 Uni',
    precio: '$130',
},
{
    id: '44', 
    imagen: 'te 3.jpg',
    nombre:'Té Virgin Islands',
    detalle: 'Te Clasico Virgin Islands Est 25 Saq',
    precio: '$105',
},
{
    id: '45', 
    imagen: 'cereal 1.jpg',
    nombre:'Cereal Bocaditos Granix',
    detalle: 'Cer.Avena Bocaditos Rell Granix Pou 180 Grm',
    precio: '$250',
},
{
    id: '46', 
    imagen: 'cereal 2.jpg',
    nombre:'Cereal Zucaritas Kellogs',
    detalle: 'Cereal Kelloggs Zucaritas Est 730 Grm',
    precio: '$710',
},
{
    id: '47', 
    imagen: 'atun.jpg',
    nombre:'Atún Ciudad del Lago',
    detalle: 'Atún Al Natural CIUDAD DEL LAGO Desmenuzado 170 Gr',
    precio: '$110',
},
{
    id: '48', 
    imagen: 'arvejas.jpg',
    nombre:'Arvejas Coto',
    detalle: 'Arvejas . Coto Bsa 300 Grm',
    precio: '$210',
},
{
    id: '49', 
    imagen: 'mayonesa.jpg',
    nombre:'Mayonesa Natura',
    detalle: 'Mayonesa NATURA Pouch 475 Gr',
    precio: '$150',
},
{
    id: '50', 
    imagen: 'mostaza.jpg',
    nombre:'Mostaza Natura',
    detalle: 'Mostaza NATURA Pouch 250 Gr',
    precio: '$90',
},
{
    id: '51', 
    imagen: 'ketchup.jpg',
    nombre:'Ketchup Natura',
    detalle: 'Ketchup NATURA Pouch 250 Gr',
    precio: '$100',
},
{
    id: '52', 
    imagen: 'chimi.jpg',
    nombre:'Chimichurri La Parmesana',
    detalle: 'Salsa Chimichurri LA PARMESANA Pet 300 Ml',
    precio: '$110',
},
{
    id: '53', 
    imagen: 'aceite.jpg',
    nombre:'Aceite de Girasol Cocinero',
    detalle: 'Aceite Girasol Plus Omega 9 Cocinero Pet 900 Ml',
    precio: '$300',
},
{
    id: '54', 
    imagen: 'aceite 2.jpg',
    nombre:'Aceite de Oliva Cañuelas',
    detalle: 'Aceite Oliva Extra Virgen CAÑUELAS Intenso 500 Ml',
    precio: '$430',
},
{
    id: '55', 
    imagen: 'sal.jpg',
    nombre:'Sal fina Dos Anclas',
    detalle: 'Sal Fina . Dos Anclas Paq 500 Grm',
    precio: '$50',
}
];
module.exports = almacen;