let carnes = 
[
{
    id: '00', 
    imagen: 'carne 1.jpg',
    nombre:'Roast Beef',
    detalle: 'Roast Beef Estancias Coto X KG',
    precio: '$815',
},
{
    id: '01', 
    imagen: 'carne 2.jpg',
    nombre:'Tapa de Asado',
    detalle: 'Tapa De Asado Especial X KG',
    precio: '$890',
},
{
    id: '02', 
    imagen: 'carne 3.jpg',
    nombre:'Tapa de Nalga',
    detalle: 'Tapa De Nalga Estancias Coto X KG',
    precio: '$930',
},
{
    id: '04', 
    imagen: 'carne 4.jpg',
    nombre:'Asado',
    detalle: 'Asado Del Medio Estancias Coto X KG',
    precio: '$1000',
},
{
    id: '05', 
    imagen: 'carne 5.jpg',
    nombre:'Picanha',
    detalle: 'Picanha Estancias Coto X KG',
    precio: '$995',
},
{
    id: '06', 
    imagen: 'carne 6.jpg',
    nombre:'Vacío',
    detalle: 'Vacío Del Centro Estancias Coto X KG',
    precio: '$1125',
},
{
    id: '07', 
    imagen: 'carne 7.jpg',
    nombre:'Carne Picada',
    detalle: 'Picada Desgrasada Estancias Coto X KG',
    precio: '$1200',
},
{
    id: '08', 
    imagen: 'carne 8.jpg',
    nombre:'Entraña',
    detalle: 'Entraña Estancias Coto X KG',
    precio: '$1045',
},
{
    id: '09', 
    imagen: 'carne 9.jpg',
    nombre:'Lomo',
    detalle: 'Lomo Estancias Coto X KG',
    precio: '$1225',
},
{
    id: '10', 
    imagen: 'carne 10.jpg',
    nombre:'Cuadril',
    detalle: 'Cuadril Selección X KG',
    precio: '$925',
},
{
    id: '11', 
    imagen: 'cordero 1.jpg',
    nombre:'Costillar de Cordero',
    detalle: 'Costillar De Cordero Congelado X Kg',
    precio: '$830',
},
{
    id: '12', 
    imagen: 'cerdo 1.jpg',
    nombre:'Carré de Cerdo',
    detalle: 'Carré De Cerdo Deshuesado Finas Hierbas X KG',
    precio: '$860',
},
{
    id: '13', 
    imagen: 'cerdo 2.jpg',
    nombre:'Chorizo de Cerdo',
    detalle: 'Chorizo De Cerdo COTO Envasado Al Vacio X Kg',
    precio: '$900',
},
{
    id: '14', 
    imagen: 'cerdo 3.jpg',
    nombre:'Bondiola de Cerdo',
    detalle: 'Bondiola De Cerdo Finas Hierbas X KG',
    precio: '$875',
},
{
    id: '15', 
    imagen: 'carne 11.jpg',
    nombre:'Molleja',
    detalle: 'Molleja X Kg',
    precio: '$1230',
},
{
    id: '16', 
    imagen: 'cerdo 5.jpg',
    nombre:'Matambre de Cerdo',
    detalle: 'Matambre De Cerdo X KG',
    precio: '$930',
},
{
    id: '17', 
    imagen: 'cerdo 6.jpg',
    nombre:'Bola de Lomo de Cerdo',
    detalle: 'Bola De Lomo De Cerdo X KG',
    precio: '$750',
},
{
    id: '18', 
    imagen: 'pollo 1.jpg',
    nombre:'Pollo entero',
    detalle: 'Pollo Entero Fresco X Uni 3 Kg',
    precio: '$800',
},
{
    id: '19', 
    imagen: 'pollo 2.jpg',
    nombre:'Medallones de Pollo y Espinaca',
    detalle: 'Medallones Pollo Y Espinaca Coto X Kg',
    precio: '$830',
},
{
    id: '20', 
    imagen: 'pollo 3.jpg',
    nombre:'Pechuga con Piel',
    detalle: 'Pechuga Con Piel X Uni (1.5 Kg) Refrigerados',
    precio: '$820',
},
{
    id: '21', 
    imagen: 'pollo 4.jpg',
    nombre:'Suprema sin Piel',
    detalle: 'Suprema Sin Piel X Kg Congelado',
    precio: '$800',
},
{
    id: '22', 
    imagen: 'pollo 5.jpg',
    nombre:'Suprema JyQ',
    detalle: 'Supremas Jamón Y Queso Coto X Kg',
    precio: '$640',
}

];

module.exports = carnes;