let limpieza = 
[
{
    id: '00', 
    imagen: 'jabon ropa 1.jpg',
    nombre:'Jabón Líquido ALA',
    detalle: 'Jabón Líq.Ropa Fina ALA Camellito Lav. A Mano 450 Ml',
    precio: '$195',
},
{
    id: '01', 
    imagen: 'jabon ropa 2.jpg',
    nombre:'Jabón en Polvo ALA',
    detalle: 'Jabón En Polvo Ala Con Perlas Suavizantes 800 G',
    precio: '$250',
},
{
    id: '02', 
    imagen: 'jabon ropa 3.jpg',
    nombre:'Jabón Líquido Matic',
    detalle: 'Jabón Líquido Matic Drive Colores Radiantes 3 Lts',
    precio: '$680',
},
{
    id: '03', 
    imagen: 'suavizante.jpg',
    nombre:'Suavizante Vivere',
    detalle: 'Suavizante Concentrado Vivere Intense Abrazo Apretado 1 L',
    precio: '$530',
},
{
    id: '04', 
    imagen: 'lavandina 1.jpg',
    nombre:'Lavandina Ayudín',
    detalle: 'Lavandina Liquida AYUDÍN Botella 1 L',
    precio: '$55',
},
{
    id: '05', 
    imagen: 'lavandina 2.jpg',
    nombre:'Lavandina Ayudín',
    detalle: 'Lavandina Ayudín Clásica Botella 4 Lts',
    precio: '$400',
},
{
    id: '06', 
    imagen: 'lavandina 3.jpg',
    nombre:'Lavandina Ayudín',
    detalle: 'Lavandina En Gel Lavanda Ayudin Bot 700 Ml',
    precio: '$145',
},
{
    id: '07', 
    imagen: 'lavavajillas 1.jpg',
    nombre:'Lavavajillas Zorro',
    detalle: 'Lavavajillas Cremoso Colage Zorro Bot 750 Ml',
    precio: '$125',
},
{
    id: '08', 
    imagen: 'lavavajillas 2.jpg',
    nombre:'Lavavajillas ALA',
    detalle: 'Lavavajillas Cristalino Lim Ala Bot 750 Ml',
    precio: '$160',
},
{
    id: '09', 
    imagen: 'lavavajillas 3.jpg',
    nombre:'Lavavajillas Magistral',
    detalle: 'Lavavajillas Multiuso Limón Magistral Bot 1.4 Ltr',
    precio: '$725',
},
{
    id: '10', 
    imagen: 'lavavajillas 4.jpg',
    nombre:'Lavavajillas Magistral',
    detalle: 'Lavavajillas Multiuso Marin Magistral Bot 1.4 Ltr',
    precio: '$725',
},
{
    id: '11', 
    imagen: 'limpia pisos 1.jpg',
    nombre:'Limp. de Sup. Lysoform',
    detalle: 'Limp. Líq. Desinfectante LYSOFORM Lavanda 1.8l',
    precio: '$280',
},
{
    id: '12', 
    imagen: 'limpia pisos 2.jpg',
    nombre:'Limp. de Sup. Ayudín',
    detalle: 'Limpiador Desinfectante AYUDÍN Lavanda 1,8 L',
    precio: '$325',
},
{
    id: '13', 
    imagen: 'limpia pisos 3.jpg',
    nombre:'Limp. de Superficies Poett',
    detalle: 'Limp. Desinfectante POETT Flores De Primavera 1.8 L',
    precio: '$235',
},
{
    id: '14', 
    imagen: 'limpia pisos 4.jpg',
    nombre:'Limp. de Superficies Poett',
    detalle: 'Limpiador Desinfectante POETT Solo Para Tí 4 L',
    precio: '$530',
},
{
    id: '15', 
    imagen: 'desinfectante.jpg',
    nombre:'Des. Ambientes Lysoform',
    detalle: 'Des. De Ambientes, Elimina Olores Lysoform 360ml',
    precio: '$240',
},
{
    id: '16', 
    imagen: 'aromatizante.jpg',
    nombre:'Arom. Amb. Lysoform',
    detalle: 'Arom. De Ambientes LYSOFORM 175 Gr',
    precio: '$1890',
},
{
    id: '17', 
    imagen: 'inodoros.jpg',
    nombre:'L. Inodoros Lysoform',
    detalle: 'Limpia Inodoros Lysoform Cja 3 X 10 Grm',
    precio: '$130',
}

];

module.exports = limpieza;