let verduleria = 
[
{
    id: '00', 
    imagen: 'banana.jpg',
    nombre:'Banana',
    detalle: 'Banana Cavendish Xkg',
    precio: '$150',
},
{
    id: '01', 
    imagen: 'manzana 1.jpg',
    nombre:'Manzana Verde',
    detalle: 'Manzana.G.Smith . Xkg',
    precio: '$310',
},
{
    id: '02', 
    imagen: 'manzana 2.jpg',
    nombre:'Manzana Roja',
    detalle: 'Manzana Royal Gala Xkg',
    precio: '$230',
},
{
    id: '03', 
    imagen: 'naranja.jpg',
    nombre:'Naranja',
    detalle: 'Naranja Ombl. Xkg',
    precio: '$150',
},
{
    id: '04', 
    imagen: 'frutilla.jpg',
    nombre:'Frutilla',
    detalle: 'Frutillas X 250 Gr',
    precio: '$280',
},
{
    id: '05', 
    imagen: 'kiwi.jpg',
    nombre:'Kiwi',
    detalle: 'Kiwi Selección X Kg',
    precio: '$630',
},
{
    id: '06', 
    imagen: 'limon.jpg',
    nombre:'Limón',
    detalle: 'Limon Bolsita Xkg',
    precio: '$145',
},
{
    id: '07', 
    imagen: 'anana.jpg',
    nombre:'Piña',
    detalle: 'Pina X Kg',
    precio: '$205',
},
{
    id: '08', 
    imagen: 'ciruela.jpg',
    nombre:'Ciruela',
    detalle: 'Ciruela X Kg',
    precio: '$225',
},
{
    id: '09', 
    imagen: 'pera.jpg',
    nombre:'Pera',
    detalle: 'Pera Packams X Kg',
    precio: '$195',
},
{
    id: '10', 
    imagen: 'uva.jpg',
    nombre:'Uva',
    detalle: 'Uva Red Globe Xkg',
    precio: '$270',
},
{
    id: '11', 
    imagen: 'mandarina.jpg',
    nombre:'Mandarina',
    detalle: 'Mandarina Nova X Kg',
    precio: '$65',
},
{
    id: '12', 
    imagen: 'palta.jpg',
    nombre:'Palta',
    detalle: 'Palta Hass Xkg',
    precio: '$625',
},
{
    id: '13', 
    imagen: 'tomate.jpg',
    nombre:'Tomate',
    detalle: 'Tomate Larga Vida Racimo X Kg',
    precio: '$665',
},
{
    id: '14', 
    imagen: 'zapallo.jpg',
    nombre:'Zapallo',
    detalle: 'Zapallo Anco Batata X Kg 1 Kgm',
    precio: '$80',
},
{
    id: '15', 
    imagen: 'zapallo 2.jpg',
    nombre:'Zapallo',
    detalle: 'Zapallo Anco En Rodajas Las Parchit Bja 350 Grm',
    precio: '$130',
},
{
    id: '16', 
    imagen: 'cebolla.jpg',
    nombre:'Cebolla',
    detalle: 'Cebolla Seleccionada En Bolsita X Kg',
    precio: '$140',
},
{
    id: '17', 
    imagen: 'cebolla ver.jpg',
    nombre:'Cebolla de Verdeo',
    detalle: 'Cebolla De Verdeo X Uni',
    precio: '$130',
},
{
    id: '18', 
    imagen: 'zanahoria.jpg',
    nombre:'Zanahoria',
    detalle: 'Zanahoria Bolsita X Kg',
    precio: '$205',
},
{
    id: '19', 
    imagen: 'lechuga.jpg',
    nombre:'Lechuga',
    detalle: 'Lechuga Francesa X Kg',
    precio: '$345',
},
{
    id: '20', 
    imagen: 'lechuga 2.jpg',
    nombre:'Lechuga',
    detalle: 'Lechuga Capuchina X Kg',
    precio: '$330',
},
{
    id: '21', 
    imagen: 'batata.jpg',
    nombre:'Batata',
    detalle: 'Batata Xkg Xkg',
    precio: '$90',
},
{
    id: '22', 
    imagen: 'papa bl.jpg',
    nombre:'Papa',
    detalle: 'Papa Blanca Bolsa X 2 Kg',
    precio: '$145',
},
{
    id: '23', 
    imagen: 'papa neg.jpg',
    nombre:'Papa',
    detalle: 'Papa Negra Selec Xkg',
    precio: '$80',
}

];


module.exports = verduleria;