let lacteos = 
[
{
    id: '00', 
    imagen: 'leche 1.jpg',
    nombre:'Leche Ciudad del Lago',
    detalle: 'Leche Larga Vida Entera CIUDAD DEL LAGO Ttb 1 L',
    precio: '$100',
},
{
    id: '01', 
    imagen: 'leche 2.jpg',
    nombre:'Leche Ciudad del Lago',
    detalle: 'Leche Larga Vida Descremada CIUDAD DEL LAGO Ttb 1 L',
    precio: '$100',
},
{
    id: '02', 
    imagen: 'leche 3.jpg',
    nombre:'Leche La Serenísima',
    detalle: 'Leche Ent.Lv Vit A/C/D/B9 X La Serenisi Ttb 1 Ltr',
    precio: '$130',
},
{
    id: '03', 
    imagen: 'leche 4.jpg',
    nombre:'Leche La Serenísima',
    detalle: 'Leche Par. Descremada LA SERENISIMA Larga Vida 1l',
    precio: '$130',
},
{
    id: '04', 
    imagen: 'leche 5.jpg',
    nombre:'Leche Sancor Bebé',
    detalle: 'Leche Inf. 4 Años Sancor Bebe Ttb 1 Ltr',
    precio: '$325',
},
{
    id: '05', 
    imagen: 'leche 6.jpg',
    nombre:'Leche Sancor Bebé',
    detalle: 'Leche Inf. 1 Año Sancor Bebe Ttb 1 Ltr',
    precio: '$335',
},
{
    id: '06', 
    imagen: 'leche 7.jpg',
    nombre:'Leche Alm. La Serenísima',
    detalle: 'LA SERENISIMA 100% Vegetal Almendra 1l',
    precio: '$375',
},
{
    id: '07', 
    imagen: 'leche 8.jpg',
    nombre:'Leche Gran. La Serenísima',
    detalle: 'Bebida Vegetal Granola La Serenisima Ttb 1 Ltr',
    precio: '$475',
},
{
    id: '08', 
    imagen: 'chocolatada.jpg',
    nombre:'Leche Choc. Cindor',
    detalle: 'Leche Chocolatada Vit B3 Cindor Ttb 1 Ltr',
    precio: '$425',
},
{
    id: '09', 
    imagen: 'yogur b1.jpg',
    nombre:'Yogur Bebible Sancor',
    detalle: 'Yogur Bebible Entero Frutilla Lechelita Sch 900 Grm',
    precio: '$125',
},
{
    id: '10', 
    imagen: 'yogur b2.jpg',
    nombre:'Yogur Bebible La Serenísima',
    detalle: 'Yogur Bebible Des. La Serenisima Frutilla 900 Gr',
    precio: '$125',
},
{
    id: '11', 
    imagen: 'yogur b3.jpg',
    nombre:'Yogur Bebible Sancor',
    detalle: 'Yogur Bebible Entero Vainilla Lechelita Sch 900 Grm',
    precio: '$125',
},
{
    id: '12', 
    imagen: 'yogur b4.jpg',
    nombre:'Yogur Bebible Ser',
    detalle: 'Yogur Bebible Descremado Probioticos Naturales Multifruta Ser Bot 190 Grm',
    precio: '$245',
},
{
    id: '13', 
    imagen: 'yogur s1.jpg',
    nombre:'Yogur Cremoso Milkaut',
    detalle: 'Yogur Cremoso Entero Vainilla Milkaut Pot 120 Grm',
    precio: '$45',
},
{
    id: '14', 
    imagen: 'yogur s2.jpg',
    nombre:'Yogur Cremoso Milkaut',
    detalle: 'Yogur Cremoso Entero Frutilla Milkaut Pot 120 Grm',
    precio: '$45',
},
{
    id: '15', 
    imagen: 'yogur s3.jpg',
    nombre:'Yogur Cremoso La Serenísima',
    detalle: 'Yogur Cremoso Light La Serenisima Vainilla 120 Gr',
    precio: '$45',
},
{
    id: '16', 
    imagen: 'queso crem 1.jpg',
    nombre:'Queso Cremoso',
    detalle: 'Cremoso PRIMERA MARCA Xkg',
    precio: '$850',
},
{
    id: '17', 
    imagen: 'queso crem 2.jpg',
    nombre:'Queso Cremon La Serenísima',
    detalle: 'Queso Cremon Cremoso LA SERENISIMA X Kg',
    precio: '$1050',
},
{
    id: '18', 
    imagen: 'queso crem 3.jpg',
    nombre:'Queso Cremon La Serenísima',
    detalle: 'Queso Cremon Light LA SERENISIMA X Kg',
    precio: '$1130',
},
{
    id: '19', 
    imagen: 'queso crema 1.jpg',
    nombre:'Queso crema Casancrem',
    detalle: 'Queso Crema Clásico Casancrem Pot 290 Grm',
    precio: '$430',
},
{
    id: '20', 
    imagen: 'queso crema 2.jpg',
    nombre:'Queso crema Casancrem',
    detalle: 'Queso Crema Light Casancrem Pot 290 Grm',
    precio: '$430',
},
{
    id: '21', 
    imagen: 'manteca 1.jpg',
    nombre:'Manteca Ciudad del Lago',
    detalle: 'Manteca CIUDAD DEL LAGO 200 Gr',
    precio: '$150',
},
{
    id: '22', 
    imagen: 'manteca 2.jpg',
    nombre:'Manteca Primer Premio',
    detalle: 'Manteca PRIMER PREMIO 200 Gr',
    precio: '$175',
},
{
    id: '23', 
    imagen: 'manteca 3.jpg',
    nombre:'Manteca La Serenísima',
    detalle: 'Manteca Multivitaminas LA SERENISIMA 100gr',
    precio: '$145',
},
{
    id: '24', 
    imagen: 'manteca 4.jpg',
    nombre:'Manteca La Serenísima',
    detalle: 'Manteca Light La Serenisima Pan 200 Grm',
    precio: '$325',
},
{
    id: '25', 
    imagen: 'crema 1.jpg',
    nombre:'Crema de Leche La Paulina',
    detalle: 'Crema De Leche LA PAULINA 350 CC',
    precio: '$225',
},
{
    id: '26', 
    imagen: 'crema 2.jpg',
    nombre:'Crema de Leche Milkaut',
    detalle: 'Crema Leche . Milkaut Pot 330 Cmq',
    precio: '$230',
},
{
    id: '27', 
    imagen: 'crema 3.jpg',
    nombre:'Crema de Leche Tregar',
    detalle: 'Crema Leche Doble Tregar Pot 350 Grm',
    precio: '$230',
},
{
    id: '28', 
    imagen: 'postre 1.jpg',
    nombre:'Postre Serenito Rocklets',
    detalle: 'Postre Sabor Vainilla Con Rocklets Pot 120 Grm',
    precio: '$305',
},
{
    id: '29', 
    imagen: 'postre 2.jpg',
    nombre:'Postre Serenito Choco',
    detalle: 'Postre Sabor Vainilla Con Choco Bombas Pot 118 Grm',
    precio: '$305',
},
{
    id: '30', 
    imagen: 'postre 3.jpg',
    nombre:'Postre Ser',
    detalle: 'Postre Sab.Dulce D/Le Ser Pot 100 Grm',
    precio: '$130',
},
{
    id: '31', 
    imagen: 'postre 4.jpg',
    nombre:'Postre Ser',
    detalle: 'Postre Sab.Vainilla Ser Pot 100 Grm',
    precio: '$130',
}

];

module.exports = lacteos;