let productos = [
    {
        id: '00', 
        imagen: 'pan 1.jpg',
        nombre:'Pan de Mesa Lactal',
        detalle: 'Pan De Mesa Blanco Lactal Bsa 500 Grm',
        precio: '$250',
    },
    {
        id: '01', 
        imagen: 'pan 2.jpg',
        nombre:'Pan de Mesa Fargo',
        detalle: 'Pan Salvado Plus Chico Fargo Bsa 350 Grm',
        precio: '$250',
    },
    {
        id: '02', 
        imagen: 'papas fritas.jpg',
        nombre:'Papas Fritas Lays',
        detalle: 'Papas Fritas Clásicas Lays Paq 249 Grm',
        precio: '$430',
    },
    {
        id: '03', 
        imagen: 'fideos 1.jpg',
        nombre:'Fideos Lucchetti',
        detalle: 'Tirabuzon LUCCHETTI Paquete 500 Gr',
        precio: '$70',
    },
    {
        id: '04', 
        imagen: 'fideos 2.jpg',
        nombre:'Fideos Lucchetti',
        detalle: 'Tirabuzon verduras LUCCHETTI Paquete 500 Gr',
        precio: '$130',
    },
    {
        id: '05', 
        imagen: 'fideos 3.jpg',
        nombre:'Fideos La Campagnola',
        detalle: 'Fid.Semola De Trig Tallarin La Campagnola Paq 500 Grm',
        precio: '$110',
    },
    {
        id: '06', 
        imagen: 'fideos 4.jpg',
        nombre:'Fideos Lucchetti',
        detalle: 'Coditos LUCCHETTI Paquete 500 Gr',
        precio: '$100',
    },
    {
        id: '07', 
        imagen: 'fideos 5.jpg',
        nombre:'Fideos Lucchetti',
        detalle: 'Mostachol LUCCHETTI Paquete 500 Gr',
        precio: '$100',
    },
    {
        id: '08', 
        imagen: 'lasagna.jpg',
        nombre:'Lasagna Matarazzo',
        detalle: 'Lasagna Matarazzo Paq 400 Grm',
        precio: '$260',
    },
    {
        id: '09', 
        imagen: 'ñoquis.jpg',
        nombre:'Ñoquis La Salteña',
        detalle: 'Ñoquis . La Salteña Ban 900 Grm',
        precio: '$400',
    },
    {
        id: '10', 
        imagen: 'capelletini.jpg',
        nombre:'Capelletini Giacomo',
        detalle: 'Capelletini Verdura Giacomo Paq 500 Grm',
        precio: '$330',
    },
    {
        id: '11', 
        imagen: 'arroz 1.jpg',
        nombre:'Arroz Ciudad del Lago',
        detalle: 'Arroz Largo Fino CIUDAD DEL LAGO Paquete 1 Kg',
        precio: '$100',
    },
    {
        id: '12', 
        imagen: 'arroz 2.jpg',
        nombre:'Arroz Gallo',
        detalle: 'Arroz Largo Fino GALLO Versátil Paquete 1 Kg',
        precio: '$115',
    },
    {
        id: '13', 
        imagen: 'arroz 3.jpg',
        nombre:'Arroz Lucchetti',
        detalle: 'Arroz Parboil LUCCHETTI Estuche X1 Kg',
        precio: '$125',
    },
    {
        id: '14', 
        imagen: 'arroz 4.jpg',
        nombre:'Arroz Molinos',
        detalle: 'Arroz Integ. . MOLINOS ALA Paq 1 Kgm',
        precio: '$160',
    },
    {
        id: '15', 
        imagen: 'harina 1.jpg',
        nombre:'Harina Favorita',
        detalle: 'Harina Trigo 000 FAVORITA Paq 1 Kgm',
        precio: '$70',
    },
    {
        id: '16', 
        imagen: 'harina 2.jpg',
        nombre:'Harina Cañuelas',
        detalle: 'Harina Ultra Refinada Cañuelas Paq 1 Kgm',
        precio: '$70',
    },
    {
        id: '17', 
        imagen: 'harina 3.jpg',
        nombre:'Harina Pureza',
        detalle: 'Harina Leudante Ultra Refinada Pureza Paq 1 Kgm',
        precio: '$150',
    },
    {
        id: '18', 
        imagen: 'galles 1.jpg',
        nombre:'Galletitas Criollitas',
        detalle: 'Galletitas . Criollitas Paq 300 Grm',
        precio: '$105',
    },
    {
        id: '19', 
        imagen: 'galles 2.jpg',
        nombre:'Galletitas OREO',
        detalle: 'Galletitas OREO Mini Clásica 50gr',
        precio: '$55',
    },
    {
        id: '20', 
        imagen: 'galles 3.jpg',
        nombre:'Galletitas Chocolinas',
        detalle: 'Gall.Dulces Chocolat Chocolinas Paq 250 Grm',
        precio: '$105',
    },
    {
        id: '21', 
        imagen: 'galles 4.jpg',
        nombre:'Galletitas Don Satur',
        detalle: 'Pepas DON SATUR Bsa 300 Grm',
        precio: '$120',
    },
    {
        id: '22', 
        imagen: 'galles 5.jpg',
        nombre:'Galletitas Opera',
        detalle: 'Gall.Rellena Opera Opera Pak 220 Grm',
        precio: '$130',
    },
    {
        id: '23', 
        imagen: 'galles 6.jpg',
        nombre:'Galletitas Bagley',
        detalle: 'Gall.Dulces Surtido Bagley Paq 390 Grm',
        precio: '$210',
    },
    {
        id: '24', 
        imagen: 'galles 7.jpg',
        nombre:'Galletitas Terrabusi',
        detalle: 'Galletitas Terrabusi VARIEDAD Clásica 610grs',
        precio: '$350',
    },
    
    {
        id: '25', 
        imagen: 'galles 8.jpg',
        nombre:'Galletitas 9 de Oro',
        detalle: 'Bizcochos Clásicos 9 De Oro Paq 215 Grm',
        precio: '$100',
    },
    
    {
        id: '26', 
        imagen: 'galles 9.jpg',
        nombre:'Galletitas 9 de Oro',
        detalle: 'Bizcochos Agridulces 9 De Oro Paq 215 Grm',
        precio: '$100',
    },
    
    {
        id: '27', 
        imagen: 'galles 10.jpg',
        nombre:'Galletitas Oreo',
        detalle: 'Galletitas Rellena Veggie Tripack Oreo Paq 354 Grm',
        precio: '$430',
    },
    
    {
        id: '28', 
        imagen: 'chocolate.jpg',
        nombre:'Chocolate Milka',
        detalle: 'Chocolate MILKA Relleno Oreo Paq 100 Grm',
        precio: '$410',
    },
    
    {
        id: '29', 
        imagen: 'chocolate 2.jpg',
        nombre:'Chocolate Milka',
        detalle: 'Chocolate Con Almendras Milka Fwp 110 Grm',
        precio: '$450',
    },
    
    {
        id: '30', 
        imagen: 'chocolate 3.jpg',
        nombre:'Alfajor Milka',
        detalle: 'Alfajor MILKA Chocolate 70 Gr X 1 Uni',
        precio: '$100',
    },
    
    {
        id: '31', 
        imagen: 'chocolate 4.jpg',
        nombre:'Chocolate Milka',
        detalle: 'Chocolate MILKA C/ Dulce De Leche Tab 67.5 Grm',
        precio: '$230',
    },
    
    {
        id: '32', 
        imagen: 'turron.jpg',
        nombre:'Turron Mani Arcor',
        detalle: 'Turron Mani ARCOR Paq 25 Grm',
        precio: '$30',
    },
    
    {
        id: '33', 
        imagen: 'gomitas.jpg',
        nombre:'Gomitas Mogul',
        detalle: 'Pastillas De Goma Rodajas Ácidas Mogul Fwp 50 Grm',
        precio: '$70',
    },
    
    {
        id: '34', 
        imagen: 'alfajor.jpg',
        nombre:'Alfajor Bon o Bon',
        detalle: 'Alfajor Bon O Bon 40 Gr X 1 Uni',
        precio: '$70',
    },
    
    {
        id: '35', 
        imagen: 'confites.jpg',
        nombre:'Sugus Confitados',
        detalle: 'Caramelos Sugus Confitados Est 50 Grm',
        precio: '$100',
    },
    {
        id: '36', 
        imagen: 'yerba 1.jpg',
        nombre:'Yerba Mate Amanda',
        detalle: 'Yerba Mate AMANDA Paquete 500 Gr',
        precio: '$180',
    },
    {
        id: '37', 
        imagen: 'yerba 2.jpg',
        nombre:'Yerba Mate Cruz de Malta',
        detalle: 'Yerba Mate CRUZ DE MALTA Con Palo Paquete 500 Gr',
        precio: '$220',
    },
    {
        id: '38', 
        imagen: 'yerba 3.jpg',
        nombre:'Yerba Mate Mañanita',
        detalle: 'Yerba Mate 4 Flex MAÑANITA 1 Kg',
        precio: '$230',
    },
    {
        id: '39', 
        imagen: 'cafe 1.jpg',
        nombre:'Café Arlistan',
        detalle: 'Café Instantaneo Torrado Selección Arlistan Fra 50 Grm',
        precio: '$230',
    },
    {
        id: '40', 
        imagen: 'cafe 2.jpg',
        nombre:'Café La Virginia',
        detalle: 'Café Molido LA VIRGINIA Paquete 250 Gr',
        precio: '$310',
    },
    {
        id: '41', 
        imagen: 'cafe 3.jpg',
        nombre:'Café Nescafe',
        detalle: 'Cafe Instantaneo Suave Nescafe Fra 100 Grm',
        precio: '$750',
    },
    {
        id: '42', 
        imagen: 'te 1.jpg',
        nombre:'Té Taragui',
        detalle: 'Te X100 Saq Filtr Taragui Est 100 Uni',
        precio: '$300',
    },
    {
        id: '43', 
        imagen: 'te 2.jpg',
        nombre:'Té La Virginia',
        detalle: 'Te Verde Citrus LA VIRGINIA Est 20 Uni',
        precio: '$130',
    },
    {
        id: '44', 
        imagen: 'te 3.jpg',
        nombre:'Té Virgin Islands',
        detalle: 'Te Clasico Virgin Islands Est 25 Saq',
        precio: '$105',
    },
    {
        id: '45', 
        imagen: 'cereal 1.jpg',
        nombre:'Cereal Bocaditos Granix',
        detalle: 'Cer.Avena Bocaditos Rell Granix Pou 180 Grm',
        precio: '$250',
    },
    {
        id: '46', 
        imagen: 'cereal 2.jpg',
        nombre:'Cereal Zucaritas Kellogs',
        detalle: 'Cereal Kelloggs Zucaritas Est 730 Grm',
        precio: '$710',
    },
    {
        id: '47', 
        imagen: 'atun.jpg',
        nombre:'Atún Ciudad del Lago',
        detalle: 'Atún Al Natural CIUDAD DEL LAGO Desmenuzado 170 Gr',
        precio: '$110',
    },
    {
        id: '48', 
        imagen: 'arvejas.jpg',
        nombre:'Arvejas Coto',
        detalle: 'Arvejas . Coto Bsa 300 Grm',
        precio: '$210',
    },
    {
        id: '49', 
        imagen: 'mayonesa.jpg',
        nombre:'Mayonesa Natura',
        detalle: 'Mayonesa NATURA Pouch 475 Gr',
        precio: '$150',
    },
    {
        id: '50', 
        imagen: 'mostaza.jpg',
        nombre:'Mostaza Natura',
        detalle: 'Mostaza NATURA Pouch 250 Gr',
        precio: '$90',
    },
    {
        id: '51', 
        imagen: 'ketchup.jpg',
        nombre:'Ketchup Natura',
        detalle: 'Ketchup NATURA Pouch 250 Gr',
        precio: '$100',
    },
    {
        id: '52', 
        imagen: 'chimi.jpg',
        nombre:'Chimichurri La Parmesana',
        detalle: 'Salsa Chimichurri LA PARMESANA Pet 300 Ml',
        precio: '$110',
    },
    {
        id: '53', 
        imagen: 'aceite.jpg',
        nombre:'Aceite de Girasol Cocinero',
        detalle: 'Aceite Girasol Plus Omega 9 Cocinero Pet 900 Ml',
        precio: '$300',
    },
    {
        id: '54', 
        imagen: 'aceite 2.jpg',
        nombre:'Aceite de Oliva Cañuelas',
        detalle: 'Aceite Oliva Extra Virgen CAÑUELAS Intenso 500 Ml',
        precio: '$430',
    },
    {
        id: '55', 
        imagen: 'sal.jpg',
        nombre:'Sal fina Dos Anclas',
        detalle: 'Sal Fina . Dos Anclas Paq 500 Grm',
        precio: '$50',
    },
    {
        id: '00',
        imagen: 'schneider 150.jpg',
        nombre:'Schneider',
        detalle: 'Cerveza Schneider 1lt. Lager',
        precio: '$136'
    },
    {
        id: '01', 
        imagen: 'heineken 340.jpg',
        nombre:'Heineken',
        detalle: 'Cerveza Heineken 1lt. Lager',
        precio: '$327',
    },
    {
        id: '02', 
        imagen: 'stella 380.jpg',
        nombre:'Stella Artois',
        detalle: 'Cerveza Stella Artois 1lt. Lager',
        precio: '$365',
    },
    {
        id: '03', 
        imagen: 'saint felic malbec 750 cc 1890.jpg',
        nombre:'Saint Felicien',
        detalle: 'Vino tinto, malbec. Saint Felicien 750cc',
        precio: '$1754',
    },
    {
        id: '04', 
        imagen: 'portillo blanco 750cc 530 chardonnay.jpg',
        nombre:'Portillo',
        detalle: 'Vino blanco, chardonnay. Portillo 750cc',
        precio: '$515',
    },
    {
        id: '05', 
        imagen: 'fernet 750cc 970.jpg',
        nombre:'Fernet Branca',
        detalle: 'Fernet Branca 750cc',
        precio: '$869',
    },
    {
        id: '06', 
        imagen: 'gin 750cc 3050.jpg',
        nombre:'Bombay Sapphire',
        detalle: 'Gin Bombay Sapphire 750cc',
        precio: '$3015',
    },
    {
        id: '07', 
        imagen: 'tanqueray 700cc 2900.jpg',
        nombre:'Tanqueray',
        detalle: 'Gin Tanqueray 700cc',
        precio: '$2783',
    },
    {
        id: '08', 
        imagen: 'corona 710cc 365.jpg',
        nombre:'Corona',
        detalle: 'Cerveza Corona 710cc',
        precio: '$345',
    },
    {
        id: '09', 
        imagen: 'ron oro 750cc 1300.jpg',
        nombre:'Bacardí',
        detalle: 'Ron Bacardí Oro 750cc',
        precio: '$1239',
    },
    {
        id: '00', 
        imagen: 'coca 2.25.png',
        nombre:'Coca-Cola',
        detalle: 'Gaseosa Coca-Cola 2.25lts Sabor Original',
        precio: '$250',
    },
    {
        id: '01', 
        imagen: 'Coca light 2.25.png',
        nombre:'Coca-Cola',
        detalle: 'Gaseosa Coca-Cola Light 2.25lts. Sin azúcares',
        precio: '$250',
    },
    {
        id: '02', 
        imagen: 'fanta 2.25.png',
        nombre:'Fanta',
        detalle: 'Gaseosa Fanta 2.25lts Sabor Naranja',
        precio: '$230',
    },
    {
        id: '03', 
        imagen: 'fanta light 2.25.png',
        nombre:'Fanta Light',
        detalle: 'Gaseosa Fanta 2.25lts Sabor Naranja. Sin azúcares',
        precio: '$230',
    },
    {
        id: '04', 
        imagen: 'sprite 2.25.png',
        nombre:'Sprite',
        detalle: 'Gaseosa Sprite 2.25lts Sabor Lima Limón',
        precio: '$230',
    },
    {
        id: '05', 
        imagen: 'sprite light 2.25.png',
        nombre:'Sprite Light',
        detalle: 'Gaseosa Sprite 2.25lts Sabor Lima Limón. Sin azúcares',
        precio: '$230',
    },
    {
        id: '06', 
        imagen: 'pepsi 2.25.png',
        nombre:'Pepsi',
        detalle: 'Gaseosa Pepsi 2.25lts Sabor Cola',
        precio: '$245',
    },
    {
        id: '07', 
        imagen: 'pepsi light 2.25.png',
        nombre:'Pepsi Light',
        detalle: 'Gaseosa Pepsi 2.25lts Sabor Cola. Sin azúcares',
        precio: '$245',
    },
    {
        id: '00', 
        imagen: 'carne 1.jpg',
        nombre:'Roast Beef',
        detalle: 'Roast Beef Estancias Coto X KG',
        precio: '$815',
    },
    {
        id: '01', 
        imagen: 'carne 2.jpg',
        nombre:'Tapa de Asado',
        detalle: 'Tapa De Asado Especial X KG',
        precio: '$890',
    },
    {
        id: '02', 
        imagen: 'carne 3.jpg',
        nombre:'Tapa de Nalga',
        detalle: 'Tapa De Nalga Estancias Coto X KG',
        precio: '$930',
    },
    {
        id: '04', 
        imagen: 'carne 4.jpg',
        nombre:'Asado',
        detalle: 'Asado Del Medio Estancias Coto X KG',
        precio: '$1000',
    },
    {
        id: '05', 
        imagen: 'carne 5.jpg',
        nombre:'Picanha',
        detalle: 'Picanha Estancias Coto X KG',
        precio: '$995',
    },
    {
        id: '06', 
        imagen: 'carne 6.jpg',
        nombre:'Vacío',
        detalle: 'Vacío Del Centro Estancias Coto X KG',
        precio: '$1125',
    },
    {
        id: '07', 
        imagen: 'carne 7.jpg',
        nombre:'Carne Picada',
        detalle: 'Picada Desgrasada Estancias Coto X KG',
        precio: '$1200',
    },
    {
        id: '08', 
        imagen: 'carne 8.jpg',
        nombre:'Entraña',
        detalle: 'Entraña Estancias Coto X KG',
        precio: '$1045',
    },
    {
        id: '09', 
        imagen: 'carne 9.jpg',
        nombre:'Lomo',
        detalle: 'Lomo Estancias Coto X KG',
        precio: '$1225',
    },
    {
        id: '10', 
        imagen: 'carne 10.jpg',
        nombre:'Cuadril',
        detalle: 'Cuadril Selección X KG',
        precio: '$925',
    },
    {
        id: '11', 
        imagen: 'cordero 1.jpg',
        nombre:'Costillar de Cordero',
        detalle: 'Costillar De Cordero Congelado X Kg',
        precio: '$830',
    },
    {
        id: '12', 
        imagen: 'cerdo 1.jpg',
        nombre:'Carré de Cerdo',
        detalle: 'Carré De Cerdo Deshuesado Finas Hierbas X KG',
        precio: '$860',
    },
    {
        id: '13', 
        imagen: 'cerdo 2.jpg',
        nombre:'Chorizo de Cerdo',
        detalle: 'Chorizo De Cerdo COTO Envasado Al Vacio X Kg',
        precio: '$900',
    },
    {
        id: '14', 
        imagen: 'cerdo 3.jpg',
        nombre:'Bondiola de Cerdo',
        detalle: 'Bondiola De Cerdo Finas Hierbas X KG',
        precio: '$875',
    },
    {
        id: '15', 
        imagen: 'carne 11.jpg',
        nombre:'Molleja',
        detalle: 'Molleja X Kg',
        precio: '$1230',
    },
    {
        id: '16', 
        imagen: 'cerdo 5.jpg',
        nombre:'Matambre de Cerdo',
        detalle: 'Matambre De Cerdo X KG',
        precio: '$930',
    },
    {
        id: '17', 
        imagen: 'cerdo 6.jpg',
        nombre:'Bola de Lomo de Cerdo',
        detalle: 'Bola De Lomo De Cerdo X KG',
        precio: '$750',
    },
    {
        id: '18', 
        imagen: 'pollo 1.jpg',
        nombre:'Pollo entero',
        detalle: 'Pollo Entero Fresco X Uni 3 Kg',
        precio: '$800',
    },
    {
        id: '19', 
        imagen: 'pollo 2.jpg',
        nombre:'Medallones de Pollo y Espinaca',
        detalle: 'Medallones Pollo Y Espinaca Coto X Kg',
        precio: '$830',
    },
    {
        id: '20', 
        imagen: 'pollo 3.jpg',
        nombre:'Pechuga con Piel',
        detalle: 'Pechuga Con Piel X Uni (1.5 Kg) Refrigerados',
        precio: '$820',
    },
    {
        id: '21', 
        imagen: 'pollo 4.jpg',
        nombre:'Suprema sin Piel',
        detalle: 'Suprema Sin Piel X Kg Congelado',
        precio: '$800',
    },
    {
        id: '22', 
        imagen: 'pollo 5.jpg',
        nombre:'Suprema JyQ',
        detalle: 'Supremas Jamón Y Queso Coto X Kg',
        precio: '$640',
    },
    {
        id: '00', 
        imagen: 'papel.jpg',
        nombre:'P.Higiénico Campanita',
        detalle: 'Papel higiénico Campanita 80mts x 4',
        precio: '$305',
    },
    {
        id: '01', 
        imagen: 'papel 2.jpg',
        nombre:'P.Higiénico Higienol',
        detalle: 'Papel higiénico Higienol Dúo 50mts x 4',
        precio: '$550',
    },
    {
        id: '02', 
        imagen: 'rollo cocina.jpg',
        nombre:'Rollo cocina Elite',
        detalle: 'Rollo de cocina Elite D/H 2 Uni.',
        precio: '$210',
    },
    {
        id: '03', 
        imagen: 'cepillo dientes 2.jpg',
        nombre:'Cepillo dental Colgate',
        detalle: 'Cepillo dental Colgate Essential Clean suave 1 Uni.',
        precio: '$70',
    },
    {
        id: '04', 
        imagen: 'cepillo dientes.jpg',
        nombre:'Cepillo dental Colgate',
        detalle: 'Cepillo dental Colgate zig-zag suave 2 Uni.',
        precio: '$185',
    },
    {
        id: '05', 
        imagen: 'pasta dental.jpg',
        nombre:'Crema Dental Colgate',
        detalle: 'Crema dental Colgate Triple Acción Xtra blancura 50g.',
        precio: '$110',
    },
    {
        id: '06', 
        imagen: 'pasta dental 2.jpg',
        nombre:'Crema Dental Sensodyne',
        detalle: 'Crema dental Sensodyne Original 50g.',
        precio: '$265',
    },
    {
        id: '07', 
        imagen: 'desodorante hom.jpg',
        nombre:'Desodorante Rexona Men',
        detalle: 'Des. Antitranspirante Rexona Xtracool aerosol 150ml',
        precio: '$300',
    },
    {
        id: '08', 
        imagen: 'desodorante muj.jpg',
        nombre:'Desodorante Rexona Women',
        detalle: 'Desodorante Antitranspirante Rexona en aerosol 110ml',
        precio: '$355',
    },
    {
        id: '09', 
        imagen: 'jabon s.jpg',
        nombre:'Jabón en barra Rexona',
        detalle: 'Jabón en barra Rexona cotton 125g',
        precio: '$75',
    },
    {
        id: '10', 
        imagen: 'jabon s2.jpg',
        nombre:'Jabón en barra Lux',
        detalle: 'Jabón en barra Lux Flor de Vainilla 3 x 135g',
        precio: '$140',
    },
    {
        id: '11', 
        imagen: 'jabon l.jpg',
        nombre:'Jabón Líquido Villeneuve',
        detalle: 'Jabón Líquido Villeneuve Coconut 240ml',
        precio: '$230',
    },
    {
        id: '12', 
        imagen: 'toallitas fem.jpg',
        nombre:'Toallitas Siempre Libre',
        detalle: 'Toallitas Adaptables Ultrafina Siempre Libre 16 Uni',
        precio: '$400',
    },
    {
        id: '13', 
        imagen: 'toallitas fem2.jpg',
        nombre:'Toallitas Always',
        detalle: 'Toallitas Always protección triple suave 16 Uni',
        precio: '$365',
    },
    {
        id: '00', 
        imagen: 'leche 1.jpg',
        nombre:'Leche Ciudad del Lago',
        detalle: 'Leche Larga Vida Entera CIUDAD DEL LAGO Ttb 1 L',
        precio: '$100',
    },
    {
        id: '01', 
        imagen: 'leche 2.jpg',
        nombre:'Leche Ciudad del Lago',
        detalle: 'Leche Larga Vida Descremada CIUDAD DEL LAGO Ttb 1 L',
        precio: '$100',
    },
    {
        id: '02', 
        imagen: 'leche 3.jpg',
        nombre:'Leche La Serenísima',
        detalle: 'Leche Ent.Lv Vit A/C/D/B9 X La Serenisi Ttb 1 Ltr',
        precio: '$130',
    },
    {
        id: '03', 
        imagen: 'leche 4.jpg',
        nombre:'Leche La Serenísima',
        detalle: 'Leche Par. Descremada LA SERENISIMA Larga Vida 1l',
        precio: '$130',
    },
    {
        id: '04', 
        imagen: 'leche 5.jpg',
        nombre:'Leche Sancor Bebé',
        detalle: 'Leche Inf. 4 Años Sancor Bebe Ttb 1 Ltr',
        precio: '$325',
    },
    {
        id: '05', 
        imagen: 'leche 6.jpg',
        nombre:'Leche Sancor Bebé',
        detalle: 'Leche Inf. 1 Año Sancor Bebe Ttb 1 Ltr',
        precio: '$335',
    },
    {
        id: '06', 
        imagen: 'leche 7.jpg',
        nombre:'Leche Alm. La Serenísima',
        detalle: 'LA SERENISIMA 100% Vegetal Almendra 1l',
        precio: '$375',
    },
    {
        id: '07', 
        imagen: 'leche 8.jpg',
        nombre:'Leche Gran. La Serenísima',
        detalle: 'Bebida Vegetal Granola La Serenisima Ttb 1 Ltr',
        precio: '$475',
    },
    {
        id: '08', 
        imagen: 'chocolatada.jpg',
        nombre:'Leche Choc. Cindor',
        detalle: 'Leche Chocolatada Vit B3 Cindor Ttb 1 Ltr',
        precio: '$425',
    },
    {
        id: '09', 
        imagen: 'yogur b1.jpg',
        nombre:'Yogur Bebible Sancor',
        detalle: 'Yogur Bebible Entero Frutilla Lechelita Sch 900 Grm',
        precio: '$125',
    },
    {
        id: '10', 
        imagen: 'yogur b2.jpg',
        nombre:'Yogur Bebible La Serenísima',
        detalle: 'Yogur Bebible Des. La Serenisima Frutilla 900 Gr',
        precio: '$125',
    },
    {
        id: '11', 
        imagen: 'yogur b3.jpg',
        nombre:'Yogur Bebible Sancor',
        detalle: 'Yogur Bebible Entero Vainilla Lechelita Sch 900 Grm',
        precio: '$125',
    },
    {
        id: '12', 
        imagen: 'yogur b4.jpg',
        nombre:'Yogur Bebible Ser',
        detalle: 'Yogur Bebible Descremado Probioticos Naturales Multifruta Ser Bot 190 Grm',
        precio: '$245',
    },
    {
        id: '13', 
        imagen: 'yogur s1.jpg',
        nombre:'Yogur Cremoso Milkaut',
        detalle: 'Yogur Cremoso Entero Vainilla Milkaut Pot 120 Grm',
        precio: '$45',
    },
    {
        id: '14', 
        imagen: 'yogur s2.jpg',
        nombre:'Yogur Cremoso Milkaut',
        detalle: 'Yogur Cremoso Entero Frutilla Milkaut Pot 120 Grm',
        precio: '$45',
    },
    {
        id: '15', 
        imagen: 'yogur s3.jpg',
        nombre:'Yogur Cremoso La Serenísima',
        detalle: 'Yogur Cremoso Light La Serenisima Vainilla 120 Gr',
        precio: '$45',
    },
    {
        id: '16', 
        imagen: 'queso crem 1.jpg',
        nombre:'Queso Cremoso',
        detalle: 'Cremoso PRIMERA MARCA Xkg',
        precio: '$850',
    },
    {
        id: '17', 
        imagen: 'queso crem 2.jpg',
        nombre:'Queso Cremon La Serenísima',
        detalle: 'Queso Cremon Cremoso LA SERENISIMA X Kg',
        precio: '$1050',
    },
    {
        id: '18', 
        imagen: 'queso crem 3.jpg',
        nombre:'Queso Cremon La Serenísima',
        detalle: 'Queso Cremon Light LA SERENISIMA X Kg',
        precio: '$1130',
    },
    {
        id: '19', 
        imagen: 'queso crema 1.jpg',
        nombre:'Queso crema Casancrem',
        detalle: 'Queso Crema Clásico Casancrem Pot 290 Grm',
        precio: '$430',
    },
    {
        id: '20', 
        imagen: 'queso crema 2.jpg',
        nombre:'Queso crema Casancrem',
        detalle: 'Queso Crema Light Casancrem Pot 290 Grm',
        precio: '$430',
    },
    {
        id: '21', 
        imagen: 'manteca 1.jpg',
        nombre:'Manteca Ciudad del Lago',
        detalle: 'Manteca CIUDAD DEL LAGO 200 Gr',
        precio: '$150',
    },
    {
        id: '22', 
        imagen: 'manteca 2.jpg',
        nombre:'Manteca Primer Premio',
        detalle: 'Manteca PRIMER PREMIO 200 Gr',
        precio: '$175',
    },
    {
        id: '23', 
        imagen: 'manteca 3.jpg',
        nombre:'Manteca La Serenísima',
        detalle: 'Manteca Multivitaminas LA SERENISIMA 100gr',
        precio: '$145',
    },
    {
        id: '24', 
        imagen: 'manteca 4.jpg',
        nombre:'Manteca La Serenísima',
        detalle: 'Manteca Light La Serenisima Pan 200 Grm',
        precio: '$325',
    },
    {
        id: '25', 
        imagen: 'crema 1.jpg',
        nombre:'Crema de Leche La Paulina',
        detalle: 'Crema De Leche LA PAULINA 350 CC',
        precio: '$225',
    },
    {
        id: '26', 
        imagen: 'crema 2.jpg',
        nombre:'Crema de Leche Milkaut',
        detalle: 'Crema Leche . Milkaut Pot 330 Cmq',
        precio: '$230',
    },
    {
        id: '27', 
        imagen: 'crema 3.jpg',
        nombre:'Crema de Leche Tregar',
        detalle: 'Crema Leche Doble Tregar Pot 350 Grm',
        precio: '$230',
    },
    {
        id: '28', 
        imagen: 'postre 1.jpg',
        nombre:'Postre Serenito Rocklets',
        detalle: 'Postre Sabor Vainilla Con Rocklets Pot 120 Grm',
        precio: '$305',
    },
    {
        id: '29', 
        imagen: 'postre 2.jpg',
        nombre:'Postre Serenito Choco',
        detalle: 'Postre Sabor Vainilla Con Choco Bombas Pot 118 Grm',
        precio: '$305',
    },
    {
        id: '30', 
        imagen: 'postre 3.jpg',
        nombre:'Postre Ser',
        detalle: 'Postre Sab.Dulce D/Le Ser Pot 100 Grm',
        precio: '$130',
    },
    {
        id: '31', 
        imagen: 'postre 4.jpg',
        nombre:'Postre Ser',
        detalle: 'Postre Sab.Vainilla Ser Pot 100 Grm',
        precio: '$130',
    },
    {
        id: '00', 
        imagen: 'jabon ropa 1.jpg',
        nombre:'Jabón Líquido ALA',
        detalle: 'Jabón Líq.Ropa Fina ALA Camellito Lav. A Mano 450 Ml',
        precio: '$195',
    },
    {
        id: '01', 
        imagen: 'jabon ropa 2.jpg',
        nombre:'Jabón en Polvo ALA',
        detalle: 'Jabón En Polvo Ala Con Perlas Suavizantes 800 G',
        precio: '$250',
    },
    {
        id: '02', 
        imagen: 'jabon ropa 3.jpg',
        nombre:'Jabón Líquido Matic',
        detalle: 'Jabón Líquido Matic Drive Colores Radiantes 3 Lts',
        precio: '$680',
    },
    {
        id: '03', 
        imagen: 'suavizante.jpg',
        nombre:'Suavizante Vivere',
        detalle: 'Suavizante Concentrado Vivere Intense Abrazo Apretado 1 L',
        precio: '$530',
    },
    {
        id: '04', 
        imagen: 'lavandina 1.jpg',
        nombre:'Lavandina Ayudín',
        detalle: 'Lavandina Liquida AYUDÍN Botella 1 L',
        precio: '$55',
    },
    {
        id: '05', 
        imagen: 'lavandina 2.jpg',
        nombre:'Lavandina Ayudín',
        detalle: 'Lavandina Ayudín Clásica Botella 4 Lts',
        precio: '$400',
    },
    {
        id: '06', 
        imagen: 'lavandina 3.jpg',
        nombre:'Lavandina Ayudín',
        detalle: 'Lavandina En Gel Lavanda Ayudin Bot 700 Ml',
        precio: '$145',
    },
    {
        id: '07', 
        imagen: 'lavavajillas 1.jpg',
        nombre:'Lavavajillas Zorro',
        detalle: 'Lavavajillas Cremoso Colage Zorro Bot 750 Ml',
        precio: '$125',
    },
    {
        id: '08', 
        imagen: 'lavavajillas 2.jpg',
        nombre:'Lavavajillas ALA',
        detalle: 'Lavavajillas Cristalino Lim Ala Bot 750 Ml',
        precio: '$160',
    },
    {
        id: '09', 
        imagen: 'lavavajillas 3.jpg',
        nombre:'Lavavajillas Magistral',
        detalle: 'Lavavajillas Multiuso Limón Magistral Bot 1.4 Ltr',
        precio: '$725',
    },
    {
        id: '10', 
        imagen: 'lavavajillas 4.jpg',
        nombre:'Lavavajillas Magistral',
        detalle: 'Lavavajillas Multiuso Marin Magistral Bot 1.4 Ltr',
        precio: '$725',
    },
    {
        id: '11', 
        imagen: 'limpia pisos 1.jpg',
        nombre:'Limp. de Sup. Lysoform',
        detalle: 'Limp. Líq. Desinfectante LYSOFORM Lavanda 1.8l',
        precio: '$280',
    },
    {
        id: '12', 
        imagen: 'limpia pisos 2.jpg',
        nombre:'Limp. de Sup. Ayudín',
        detalle: 'Limpiador Desinfectante AYUDÍN Lavanda 1,8 L',
        precio: '$325',
    },
    {
        id: '13', 
        imagen: 'limpia pisos 3.jpg',
        nombre:'Limp. de Superficies Poett',
        detalle: 'Limp. Desinfectante POETT Flores De Primavera 1.8 L',
        precio: '$235',
    },
    {
        id: '14', 
        imagen: 'limpia pisos 4.jpg',
        nombre:'Limp. de Superficies Poett',
        detalle: 'Limpiador Desinfectante POETT Solo Para Tí 4 L',
        precio: '$530',
    },
    {
        id: '15', 
        imagen: 'desinfectante.jpg',
        nombre:'Des. Ambientes Lysoform',
        detalle: 'Des. De Ambientes, Elimina Olores Lysoform 360ml',
        precio: '$240',
    },
    {
        id: '16', 
        imagen: 'aromatizante.jpg',
        nombre:'Arom. Amb. Lysoform',
        detalle: 'Arom. De Ambientes LYSOFORM 175 Gr',
        precio: '$1890',
    },
    {
        id: '17', 
        imagen: 'inodoros.jpg',
        nombre:'L. Inodoros Lysoform',
        detalle: 'Limpia Inodoros Lysoform Cja 3 X 10 Grm',
        precio: '$130',
    },
    {
        id: '00', 
        imagen: 'banana.jpg',
        nombre:'Banana',
        detalle: 'Banana Cavendish Xkg',
        precio: '$150',
    },
    {
        id: '01', 
        imagen: 'manzana 1.jpg',
        nombre:'Manzana Verde',
        detalle: 'Manzana.G.Smith . Xkg',
        precio: '$310',
    },
    {
        id: '02', 
        imagen: 'manzana 2.jpg',
        nombre:'Manzana Roja',
        detalle: 'Manzana Royal Gala Xkg',
        precio: '$230',
    },
    {
        id: '03', 
        imagen: 'naranja.jpg',
        nombre:'Naranja',
        detalle: 'Naranja Ombl. Xkg',
        precio: '$150',
    },
    {
        id: '04', 
        imagen: 'frutilla.jpg',
        nombre:'Frutilla',
        detalle: 'Frutillas X 250 Gr',
        precio: '$280',
    },
    {
        id: '05', 
        imagen: 'kiwi.jpg',
        nombre:'Kiwi',
        detalle: 'Kiwi Selección X Kg',
        precio: '$630',
    },
    {
        id: '06', 
        imagen: 'limon.jpg',
        nombre:'Limón',
        detalle: 'Limon Bolsita Xkg',
        precio: '$145',
    },
    {
        id: '07', 
        imagen: 'anana.jpg',
        nombre:'Piña',
        detalle: 'Pina X Kg',
        precio: '$205',
    },
    {
        id: '08', 
        imagen: 'ciruela.jpg',
        nombre:'Ciruela',
        detalle: 'Ciruela X Kg',
        precio: '$225',
    },
    {
        id: '09', 
        imagen: 'pera.jpg',
        nombre:'Pera',
        detalle: 'Pera Packams X Kg',
        precio: '$195',
    },
    {
        id: '10', 
        imagen: 'uva.jpg',
        nombre:'Uva',
        detalle: 'Uva Red Globe Xkg',
        precio: '$270',
    },
    {
        id: '11', 
        imagen: 'mandarina.jpg',
        nombre:'Mandarina',
        detalle: 'Mandarina Nova X Kg',
        precio: '$65',
    },
    {
        id: '12', 
        imagen: 'palta.jpg',
        nombre:'Palta',
        detalle: 'Palta Hass Xkg',
        precio: '$625',
    },
    {
        id: '13', 
        imagen: 'tomate.jpg',
        nombre:'Tomate',
        detalle: 'Tomate Larga Vida Racimo X Kg',
        precio: '$665',
    },
    {
        id: '14', 
        imagen: 'zapallo.jpg',
        nombre:'Zapallo',
        detalle: 'Zapallo Anco Batata X Kg 1 Kgm',
        precio: '$80',
    },
    {
        id: '15', 
        imagen: 'zapallo 2.jpg',
        nombre:'Zapallo',
        detalle: 'Zapallo Anco En Rodajas Las Parchit Bja 350 Grm',
        precio: '$130',
    },
    {
        id: '16', 
        imagen: 'cebolla.jpg',
        nombre:'Cebolla',
        detalle: 'Cebolla Seleccionada En Bolsita X Kg',
        precio: '$140',
    },
    {
        id: '17', 
        imagen: 'cebolla ver.jpg',
        nombre:'Cebolla de Verdeo',
        detalle: 'Cebolla De Verdeo X Uni',
        precio: '$130',
    },
    {
        id: '18', 
        imagen: 'zanahoria.jpg',
        nombre:'Zanahoria',
        detalle: 'Zanahoria Bolsita X Kg',
        precio: '$205',
    },
    {
        id: '19', 
        imagen: 'lechuga.jpg',
        nombre:'Lechuga',
        detalle: 'Lechuga Francesa X Kg',
        precio: '$345',
    },
    {
        id: '20', 
        imagen: 'lechuga 2.jpg',
        nombre:'Lechuga',
        detalle: 'Lechuga Capuchina X Kg',
        precio: '$330',
    },
    {
        id: '21', 
        imagen: 'batata.jpg',
        nombre:'Batata',
        detalle: 'Batata Xkg Xkg',
        precio: '$90',
    },
    {
        id: '22', 
        imagen: 'papa bl.jpg',
        nombre:'Papa',
        detalle: 'Papa Blanca Bolsa X 2 Kg',
        precio: '$145',
    },
    {
        id: '23', 
        imagen: 'papa neg.jpg',
        nombre:'Papa',
        detalle: 'Papa Negra Selec Xkg',
        precio: '$80',
    }
    ];

    module.exports = productos;

    